CREATE TABLE [dbo].[Book]
(
	[ISBN] VARCHAR(20) PRIMARY KEY NOT NULL,
	[Title] VARCHAR(200) NOT NULL,
	[Year] VARCHAR(20) NOT NULL,
	[AuthorID] VARCHAR(20) NOT NULL,
	[StudentID] VARCHAR(20) NULL, 
	CONSTRAINT FK_AuthorID FOREIGN KEY (AuthorID) REFERENCES Author (AuthorID),
	CONSTRAINT FK_StudnetID FOREIGN KEY (StudentID) REFERENCES Student (StudentID),
)
