CREATE TABLE [dbo].[Student]
(
	[StudentID] VARCHAR(20) NOT NULL PRIMARY KEY,
	[FirstName] VARCHAR(20) NOT NULL,
	[LastName] VARCHAR(20) NOT NULL,
	[Email] VARCHAR(50) NOT NULL,
	[Mobile] INT NOT NULL,
)
